version: '3.8'

services:
  db:
    build: .
    environment:
      POSTGRES_DB: enqueldb
      POSTGRES_USER: enqueluser
      POSTGRES_PASSWORD: enquelpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: